[package]
name = "scrapping"
version = "0.1.0"
edition = "2025"

[dependencies]
csv = "1.3.1"
fxhash = "0.2.1"
scraper = "0.24.0"


[dependencies.pyo3]
version = "0.26.0"
features = ["extension-module"]


[package.metadata.maturin]
name = "scrapping"
